apiVersion: v1
kind: Namespace
metadata:
  name: test
---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: cirros
  namespace: test
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/size: small
        kubevirt.io/domain: cirros
    spec:
      domain:
        devices:
          disks:
            - name: containerdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
            - name: default
              masquerade: {}
        resources:
          requests:
            memory: 64M
      networks:
        - name: default
          pod: {}
      volumes:
        - name: containerdisk
          containerDisk:
            image: quay.io/kubevirt/cirros-container-disk-demo
        - name: cloudinitdisk
          cloudInitNoCloud:
            userDataBase64: SGkuXG4=
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cirros-vnc
  namespace: test
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cirros-vnc
  namespace: test
subjects:
  - kind: ServiceAccount
    name: cirros-vnc
    namespace: test
roleRef:
  kind: Role
  name: cirros-vnc
  apiGroup: rbac.authorization.k8s.io
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cirros-vnc
  namespace: test
rules:
  - apiGroups:
      - subresources.kubevirt.io
    resources:
      - virtualmachineinstances/console
      - virtualmachineinstances/vnc
    verbs:
      - get
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cirros-vnc
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cirros-vnc
  template:
    metadata:
      labels:
        app: cirros-vnc
    spec:
      serviceAccountName: cirros-vnc
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Equal"
          value: ""
          effect: "NoSchedule"
        - key: "node-role.kubernetes.io/master"
          operator: "Equal"
          value: ""
          effect: "NoSchedule"
      containers:
        - name: cirros-vnc
          image: poneding/virt-vnc
          env:
            - name: VM_NAMESPACE
              value: test
            - name: VM_NAME
              value: cirros
          ports:
            - name: vnc
              containerPort: 8080
          livenessProbe:
            httpGet:
              port: 8080
              path: /
              scheme: HTTP
            failureThreshold: 30
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: cirros-vnc
  name: cirros-vnc
  namespace: test
spec:
  ports:
    - name: vnc
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: cirros-vnc
  type: NodePort
